// dev-only: full interactive run with timed screenshots
import puppeteer from 'puppeteer-core';
const browser = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new', args: ['--enable-gpu', '--ignore-gpu-blocklist', '--use-angle=d3d11', '--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage();
await page.setViewport({ width: 1280, height: 720 });
const logs = [];
page.on('console', (m) => { if (['error'].includes(m.type())) logs.push(`[${m.type()}] ${m.text()}`); });
page.on('pageerror', (e) => logs.push(`[pageerror] ${e.message}`));
await page.goto('http://localhost:5173/', { waitUntil: 'load' });
await page.waitForFunction('!document.querySelector("#enter").disabled', { timeout: 120000 });
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const snap = async (n) => { await page.screenshot({ path: `.shots/f5_${n}.png` }); };
await page.click('#enter');
await wait(1500); await snap('1_walk_a');
await wait(1200); await snap('2_walk_b');
await wait(5000); await snap('3_greet');
await page.keyboard.press('KeyR'); await wait(700); await snap('4_scare');
await wait(2500);
await page.keyboard.press('KeyB'); await wait(2500); await snap('5_dance');
await page.keyboard.press('KeyB');
await page.keyboard.press('KeyV'); await wait(2500); await snap('6_villain');
await page.keyboard.press('KeyV'); await wait(1500);
await page.mouse.click(300, 520); await wait(2500); await snap('7_stroll');
await page.keyboard.down('Space'); await wait(13000); await page.keyboard.up('Space'); await wait(800); await snap('8_quota');
await page.keyboard.press('Tab'); await wait(400);
await page.click('.seg[data-key="mode"] button[data-v="1"]'); await wait(800); await snap('9_clay');
await page.click('.seg[data-key="mode"] button[data-v="wire"]'); await wait(800); await snap('10_wire');
const err = await page.$eval('#error', (e) => (e.classList.contains('hidden') ? '' : e.textContent));
console.log('error box:', err || '(none)');
console.log(logs.slice(0, 20).join('\n'));
await browser.close();
